POST http://localhost:3000/guess_game
content-type: application/json

{
  "guess": 40
}

###

POST http://localhost:3000/credentials
content-type: application/json

{
  "username": "hugh",
  "password": "swordfish"
}